### ISSUE TITLE
Readme links not workiny anymore

### ISSUE THREAD

**Issue by LuposX** [I-Al-Istannen/MiMaInterpreter#1]
The Download button and the issue button in the readme dont work  anymore.

**Comment by I-Al-Istannen** [comment]
That is true, I migrated off of that infrastructure. I should probably add a Github release instead :)

**Comment by I-Al-Istannen** [comment]
I think I fixed them and built https://github.com/I-Al-Istannen/MiMaInterpreter/releases/tag/v1.0.

Ideally, I would build a standalone executable (e.g. via Jpackage) and update this to use Jigsaw, but I currently don't have the time for it.
